sudo: required

env:
  - test: CentOS 7 Apache
    distribution: centos
    version: 7
    init: /usr/lib/systemd/systemd
    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
    script_opts: "--server-webserver=apache"
  - test: CentOS 7 NGINX
    distribution: centos
    version: 7
    init: /usr/lib/systemd/systemd
    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
    script_opts: "--server-webserver=nginx"
  - test: Ubuntu 14.04 Apache
    distribution: ubuntu
    version: 14.04
    init: /sbin/init
    run_opts: ""
    script_opts: "--server-webserver=apache"
  - test: Ubuntu 14.04 Nginx
    distribution: ubuntu
    version: 14.04
    init: /sbin/init
    run_opts: ""
    script_opts: "--server-webserver=nginx"

addons:
  hosts:
    - devshop.travis
    - dev.projectname.devshop.travis
    - live.projectname.devshop.travis
    - dev.drup.devshop.travis

services:
  - docker

before_install:
  # Clone devshop
  - export DEVSHOP_VERSION=1.x
  - git clone http://github.com/opendevshop/devshop
  - cd devshop
  - git checkout -qf ${DEVSHOP_VERSION}
  - git status
  - echo projects[devmaster][download][type] = "copy" >> build-devmaster.make
  - echo projects[devmaster][download][url] = "/usr/share/devshop/devmaster" >> build-devmaster.make
  - cat build-devmaster.make
  - cd ..

  # Pull container
  - 'sudo docker pull ${distribution}:${version}'
  # Customize container
  - 'sudo docker build --rm=true --file=devshop/tests/Dockerfile.${distribution}-${version} --tag=${distribution}-${version}:ansible devshop/tests'

script:
  - container_id=$(mktemp)
    # Run container in detached state
  - 'sudo docker run --detach --name devshop_container --volume="${PWD}/devshop":/usr/share/devshop:rw --volume="${PWD}":/usr/share/devshop/devmaster:rw ${run_opts} -h devshop.travis --add-host "dev.drup.devshop.travis dev.projectname.devshop.travis live.projectname.devshop.travis":127.0.0.1 ${distribution}-${version}:ansible "${init}" > "${container_id}"'

  # Install script.
  - 'sudo docker exec --tty devshop_container env TRAVIS=true TERM=xterm /usr/share/devshop/install.sh ${script_opts} --hostname=devshop.travis --makefile=/usr/share/devshop/devmaster/build-devmaster-test.make'

  # Hostmaster Status
  - 'sudo docker exec devshop_container env TERM=xterm sudo su - aegir -c "drush @hostmaster status"'

  # Turn off hosting queued, and the hosting task queue.
  - 'sudo docker exec devshop_container env sudo su - aegir -c "drush @hostmaster dis hosting_queued -y -v"'
  - 'sudo docker exec devshop_container env sudo su - aegir -c "drush @hostmaster vset hosting_queue_tasks_enabled 0 -y"'

  # Build and Run Tests
  - 'sudo docker exec devshop_container env TERM=xterm sudo su - -c "cd /usr/share/devshop/tests && composer update"'
  - 'sudo docker exec devshop_container env TERM=xterm sudo su - aegir -c "devshop devmaster:test"'

  # Stop container.
  - 'sudo docker stop devshop_container'
